pipeline {
agent any
stages {
stage("Checkout") {
steps {
git url: 'https://github.com/tutranvan156/Microservices.git'
}

}
stage("Compile-in-jenkins") {
    steps {
        sh "./mvnw compile"
    }
}
}
}